\newrgbcolor{goldenrod}{.80392 .60784 .11373}
\newrgbcolor{darkgoldenrod}{.5451 .39608 .03137}
\newrgbcolor{brown}{.15 .15 .15}
\newrgbcolor{darkolivegreen}{.33333 .41961 .18431}


\def\gold#1{{\goldenrod #1}}
\def\dgold#1{{\darkgoldenrod #1}}
\def\brw#1{{\brown #1}}
\def\dkb#1{{\darkblue #1}}
\def\tdkb#1{\textbf{\darkblue #1}}
%\def\gre#1{{\green #1}}
\def\gre#1{{\darkolivegreen #1}}
\def\gry#1{{\gray #1}}
\def\rdb#1{{\red #1}}

